export type MouseButton = number;
export type KeyboardKey = number;
/**
 * Define all keyboard key codes.
 */
export type KeyboardKeys = KeyboardKey;
export namespace KeyboardKeys {
    export const backspace: number;
    export const tab: number;
    export const enter: number;
    export const shift: number;
    export const ctrl: number;
    export const alt: number;
    const _break: number;
    export { _break as break };
    export const caps_lock: number;
    export const escape: number;
    export const page_up: number;
    export const page_down: number;
    export const end: number;
    export const home: number;
    export const left: number;
    export const up: number;
    export const right: number;
    export const down: number;
    export const insert: number;
    const _delete: number;
    export { _delete as delete };
    export const space: number;
    export const n0: number;
    export const n1: number;
    export const n2: number;
    export const n3: number;
    export const n4: number;
    export const n5: number;
    export const n6: number;
    export const n7: number;
    export const n8: number;
    export const n9: number;
    export const a: number;
    export const b: number;
    export const c: number;
    export const d: number;
    export const e: number;
    export const f: number;
    export const g: number;
    export const h: number;
    export const i: number;
    export const j: number;
    export const k: number;
    export const l: number;
    export const m: number;
    export const n: number;
    export const o: number;
    export const p: number;
    export const q: number;
    export const r: number;
    export const s: number;
    export const t: number;
    export const u: number;
    export const v: number;
    export const w: number;
    export const x: number;
    export const y: number;
    export const z: number;
    export const left_window_key: number;
    export const right_window_key: number;
    export const select_key: number;
    export const numpad_0: number;
    export const numpad_1: number;
    export const numpad_2: number;
    export const numpad_3: number;
    export const numpad_4: number;
    export const numpad_5: number;
    export const numpad_6: number;
    export const numpad_7: number;
    export const numpad_8: number;
    export const numpad_9: number;
    export const multiply: number;
    export const add: number;
    export const subtract: number;
    export const decimal_point: number;
    export const divide: number;
    export const f1: number;
    export const f2: number;
    export const f3: number;
    export const f4: number;
    export const f5: number;
    export const f6: number;
    export const f7: number;
    export const f8: number;
    export const f9: number;
    export const f10: number;
    export const f11: number;
    export const f12: number;
    export const numlock: number;
    export const scroll_lock: number;
    export const semicolon: number;
    export const equal_sign: number;
    export const plus: number;
    export const comma: number;
    export const dash: number;
    export const minus: number;
    export const period: number;
    export const forward_slash: number;
    export const grave_accent: number;
    export const open_bracket: number;
    export const back_slash: number;
    export const close_braket: number;
    export const single_quote: number;
}
/**
 * Define mouse button codes.
 */
export type MouseButtons = MouseButton;
export namespace MouseButtons {
    const left_1: number;
    export { left_1 as left };
    export const middle: number;
    const right_1: number;
    export { right_1 as right };
}
//# sourceMappingURL=key_codes.d.ts.map