/**
 * Texture filter modes, determine how to scale textures.
 */
export enum TextureFilterModes {
	NEAREST = "NEAREST",
	LINEAR = "LINEAR",
	NEAREST_MIPMAP_NEAREST = "NEAREST_MIPMAP_NEAREST",
	LINEAR_MIPMAP_NEAREST = "LINEAR_MIPMAP_NEAREST",
	NEAREST_MIPMAP_LINEAR = "NEAREST_MIPMAP_LINEAR",
	LINEAR_MIPMAP_LINEAR = "LINEAR_MIPMAP_LINEAR",
};
