export = TextureInAtlasAsset;
/**
 * A texture that is part of a texture atlas.
 * Stores a texture that was generated by the texture atlas + the source rectangle in texture for this segment.
 */
declare class TextureInAtlasAsset extends TextureAssetBase {
    /** @inheritdoc */
    constructor(url: any, texture: any, sourceRect: any, atlas: any);
    _texture: any;
    _sourceRect: any;
    _atlas: any;
    /**
     * Return the source rectangle in texture atlas.
     * @returns {Rectangle} Source rectangle.
     */
    get sourceRectangle(): Rectangle;
    /**
     * Return the source rectangle in texture atlas, in normalized 0.0-1.0 values.
     * @returns {Rectangle} Source rectangle.
     */
    get sourceRectangleNormalized(): Rectangle;
    _sourceRectNormalized: Rectangle;
    /**
     * Return the texture asset of this atlas texture.
     * @returns {TextureAsset} Texture asset.
     */
    get texture(): TextureAsset;
    /**
     * Return the texture atlas class.
     * @returns {TextureAtlasAsset} Parent atlas.
     */
    get atlas(): TextureAtlasAsset;
    /** @inheritdoc */
    get image(): any;
    /** @inheritdoc */
    get width(): any;
    /** @inheritdoc */
    get height(): any;
    /** @inheritdoc */
    get _glTexture(): any;
}
import TextureAssetBase = require("./texture_asset_base");
import Rectangle = require("../utils/rectangle");
//# sourceMappingURL=texture_in_atlas_asset.d.ts.map